project/homepage/urls.py
"""
urls for homepage
"""
import django
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r"^", include("profiles.urls", namespace="profiles")),
    url(r"^admin/", include("applications.admin_urls", namespace="admin")),
    url(r"^django/admin/", admin.site.urls),
    # url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^requests/", include("applications.requests_urls", namespace="requests")),
    url(r"^documents/", include("documents.urls", namespace="documents")),
    url(r"^", include("applications.urls", namespace="applications")),
    url(r'^settings/$', views.user_settings, name='user_settings'),
    url(r'^resources/$', views.user_resources, name='user_resources'),
    url(r"^settings/", include("applications.settings_urls", namespace="settings")),



    url(r'^password-reset/$', django.contrib.auth.views.password_reset, name='password_reset'),

    url(r'^password-reset/done/$', django.contrib.auth.views.password_reset_done, name='password_reset_done'),

    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        django.contrib.auth.views.password_reset_confirm, name='password_reset_confirm'),

    url(r'^password-reset/complete/$', django.contrib.auth.views.password_reset_complete,
        name='password_reset_complete'),
]

project/pairings/models.py
from django.db import models
# from profiles.models import Restaurant, Program, Schedule
# Create your models here.

class Pairing(models.Model):
    created_at = models.DateTimeField()
    restaurant_id = models.ForeignKey('profiles.Restaurant', related_name='restaurant',\
                                      on_delete=models.DO_NOTHING)
    program_id = models. ForeignKey('profiles.Program', related_name="program",\
                                    on_delete=models.DO_NOTHING)
    schedule_id = models.ForeignKey('profiles.Schedule', related_name='schedule',\
                                    on_delete=models.DO_NOTHING)

project/homepage/views.py
"""views"""
from django.shortcuts import render, redirect
import datetime
from profiles.models import Restaurant, Schedule, Program
from applications.models import Pairings, PairingsManager, Notification
from applications.models import ApplicationReview
from documents.models import Document
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from homepage.settings import GOOGLE_API_KEY
from homepage import email_vendor
from django.contrib.auth.forms import PasswordResetForm
from django.core.files.storage import FileSystemStorage
import os
from django.db.models import Q
import mimetypes
from django.http import StreamingHttpResponse

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_DIR = os.path.join(BASE_DIR,'static')
IMAGES_DIR = os.path.join(STATIC_DIR, 'images')
ICON_DIR = os.path.join(IMAGES_DIR, 'icon')
PROFILE_IMG_DIR = os.path.join(ICON_DIR, 'profile_image')



def __get_model(user):
    # get model of restaurant or program
    type_dict = {'RE': 'restaurant', 'PR': 'program'}
    model = getattr(user.user_object, type_dict[user.user_object.type])
    return model


@login_required(login_url='/login')
def apply(request):
    user = request.user

    if user.user_type == 'ADM':
        return redirect('/admin/applications')

    model = __get_model(user)

    # Check if already applied and approved
    if model and not model.review:
        return redirect('/')

    if request.method == 'POST':

        position = request.POST.get('position')
        phone_number = request.POST.get('phone_number')
        meals = request.POST.get('meals')
        address = request.POST.get('address')

        created_at = datetime.datetime.now()
        latitude = request.POST.get('lat')
        longitude = request.POST.get('lng')

        # Create schedule model
        monday_start = tuesday_start = wednesday_start = None
        thursday_start = friday_start = saturday_start = sunday_start = None

        if user.user_object.type == 'RE':
            schedule_available = request.POST.get('schedule_available')

            if schedule_available == 'True':
                monday_start = '15:00'
                tuesday_start = '15:00'
                wednesday_start = '15:00'
                thursday_start = '15:00'
                friday_start = '15:00'
        else:
            schedule = request.POST.getlist('schedule')
            start_time = request.POST.get('start_time')
            for day in schedule:
                if day =='MO':
                    monday_start = start_time
                elif day =='TU':
                    tuesday_start = start_time
                elif day =='WE':
                    wednesday_start = start_time
                elif day =='TH':
                    thursday_start = start_time
                elif day =='FR':
                    friday_start = start_time
                elif day =='SA':
                    saturday_start = start_time
                elif day =='SU':
                    sunday_start = start_time

        schedule_model = Schedule.objects.get_or_create(monday_start=monday_start,\
                                            tuesday_start=tuesday_start,\
                                            wednesday_start=wednesday_start,\
                                            thursday_start=thursday_start,\
                                            friday_start=friday_start,\
                                            saturday_start=saturday_start,\
                                            sunday_start=sunday_start)[0]
        schedule_model.save()

        # create application review
        app_review = ApplicationReview.objects.create(created_at=created_at,\
                                                        type=user.user_object.type,
                                                        model_id=user,
                                                        status='P')
        app_review.save()

        # create new notification
        notification = Notification.objects.get_or_create(notification_type='A', is_dismissed=False, \
                                           application=app_review)[0]
        notification.save()

        # send emails
        email_vendor.email_admin_new_application(app_review)
        email_vendor.email_user_new_application(app_review)

        if user.user_object.type == 'RE':
            name = request.POST.get('company_name')
            uber_eats = request.POST.get('uber_eats')
            health_certificate = request.POST.get('health_certificate')

            if not model:
                # Create Restaurant model
                restaurant = Restaurant.objects.get_or_create(created_at=created_at,\
                                                      company_name=name,\
                                                      main_contact=user,\
                                                      phone_number=phone_number,\
                                                      schedule=schedule_model,\
                                                      meals=meals,\
                                                      uber_eats=uber_eats,\
                                                      health_certificate=health_certificate,\
                                                      address=address,\
                                                              longitude=longitude, \
                                                              latitude = latitude, \
                                                      review=app_review)[0]
            else:
                restaurant = model
                restaurant.company_name = name
                restaurant.phone_number = phone_number
                restaurant.schedule = schedule_model
                restaurant.meals = meals
                restaurant.uber_eats = uber_eats
                restaurant.health_certificate = health_certificate
                restaurant.address = address
                restaurant.review = app_review
                # restaurant.coordinates = coordinates
                restaurant.longitude = longitude
                restaurant.latitude = latitude

            restaurant.save()
            user.user_object.restaurant = restaurant
        else:
            name = request.POST.get('program_name')

            if not model:
                # Create Program model
                program = Program.objects.get_or_create(created_at=created_at,\
                                                      program_name=name,\
                                                      main_contact=user,\
                                                      phone_number=phone_number,\
                                                      schedule=schedule_model,\
                                                      meals=meals,\
                                                      address=address,\
                                                      # coordinates=coordinates,\
                                                        longitude=longitude,\
                                                        latitude=latitude,\
                                                      review=app_review)[0]
            else:
                program = model
                program.program_name = name
                program.phone_number = phone_number
                program.schedule = schedule_model
                program.meals = meals
                program.address = address
                program.review = app_review
                program.coordinates = coordinates
                program.longitude = longitude
                program.latitude = latitude

            program.save()
            user.user_object.program = program

        user.user_object.position = position
        user.user_object.save()

        user.phone_number = phone_number
        user.save()
        return redirect('/application/status')
    else:
        # GET Request

        # Check if already applied
        if model and model.review:
            return redirect('/application/status')

        return render(request, 'applications/apply.html', {'user': user})

@login_required(login_url='/login')
def apply_status(request):
    user = request.user

    if user.user_type == 'ADM':
        return redirect('/admin/applications')

    # Redirect to admin homepage is admin user signed in
    if user.user_type == 'ADM':
        return redirect('/admin/')

    model = __get_model(user)

    # Check if approved
    if not model.review:
        return redirect('/')

    return render(request, 'applications/application_status.html', {'user': user,\
        'schedule': model.schedule, 'review': model.review})


@login_required(login_url='/login')
def homepage(request):
    current_user = request.user

    # Redirect to admin homepage is admin user signed in
    if current_user.user_type == 'ADM':
        return redirect('/admin/')

    model = __get_model(current_user)

    # Has not applied
    if not model:
        return redirect('/apply/')
    elif model.review:
        # Application not approved
        return redirect('/application/status/')

    # Get partner (paired) information
    pairing_info = []

    schedule = model.schedule.getSchedule()
    schedule['monday_start_meals'] = 0
    schedule['tuesday_start_meals'] = 0
    schedule['wednesday_start_meals'] = 0
    schedule['thursday_start_meals'] = 0
    schedule['friday_start_meals'] = 0

    if current_user.user_object.type == 'PR':
        all_pairings = Pairings.objects.filter(program_id=current_user.user_object.program)
        for pairing in all_pairings:

            if not schedule['monday_start']:
                schedule['monday_start'] = pairing.restaurant_id.schedule.monday_start
            if pairing.restaurant_id.schedule.monday_start:
                schedule['monday_start_meals'] += pairing.meals

project/templates/homepage/admin-homepage.html
{% extends "../base.html" %}

	{% block head_title %}
    	<title>Dashboard</title>
	{% endblock %}

{% block body_block %}



	<div class="row m-t-25">
		<div class="col-sm-6 col-lg-3">
				<div class="overview-item overview-item--c1">
						<div class="overview__inner">
								<div class="overview-box clearfix">
										<div class="icon">
												<i class="zmdi zmdi-mood"></i>
										</div>
										<div class="text">
												<h2>{{ meal_count }}</h2>
												<span>Meals Served</span>
										</div>
								</div>
						</div>
				</div>
		</div>
		<div class="col-sm-6 col-lg-3">
				<div class="overview-item overview-item--c1">
						<div class="overview__inner">
								<div class="overview-box clearfix">
										<div class="icon">
												<i class="zmdi zmdi-cutlery"></i>
										</div>
										<div class="text">
												<h2>{{ restaurant_count }}</h2>
												<span>Restaurants</span>
										</div>
								</div>
						</div>
				</div>
		</div>
		<div class="col-sm-6 col-lg-3">
				<div class="overview-item overview-item--c1">
						<div class="overview__inner">
								<div class="overview-box clearfix">
										<div class="icon">
												<i class="zmdi zmdi-developer-board"></i>
										</div>
										<div class="text">
												<h2>{{ program_count }}</h2>
												<span>Programs</span>
										</div>
								</div>
						</div>
				</div>
		</div>
		<div class="col-sm-6 col-lg-3">
				<div class="overview-item overview-item--c1">
						<div class="overview__inner">
								<div class="overview-box clearfix">
										<div class="icon">
												<i class="zmdi zmdi-flare"></i>
										</div>
										<div class="text">
												<h2>{{ application_count }}</h2>
												<span>Applications</span>
										</div>
								</div>
						</div>
				</div>
		</div>
	</div>

  <div class="row">
      <div class="col-md-12">
          <div class="overview-wrap">
              <h2 class="title-1">Today's Schedule ({{todays_date}})</h2>
          </div>
      </div>
  </div>

  <div class="row m-t-25">
      <div class="col-lg-12">
          <div class="table-responsive table--no-card m-b-40">
              <table id="todays-schedule" class="table table-borderless table-striped table-earning">
                  <thead>
                      <tr>
                          <th>Program</th>
                          <th>Restaurant</th>
                          <th>Time</th>
                          <th>Meals</th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for schedule in daily_schedule %}
                        <!-- [company_name, program_name, wekkday_start_time, company_owner_first_name,
        # company_owner_last_name,  num_meals] -->
                          <tr>
                              <td>
																<a href="{% url 'admin:program' id=schedule.7 %}">
																	{{schedule.1}}
																</a>
															</td>
                              <td>
																<a href="{% url 'admin:restaurant' id=schedule.6 %}">
																	{{schedule.0}}
																</a>
															</td>
                              <td>{{schedule.2}}</td>
                              <td>{{schedule.5}}</td>
                          </tr>
                      {% endfor%}
                  </tbody>
              </table>
          </div>
      </div>
  </div>

{% endblock %}

project/templates/homepage/endUser-homepage.html
{% extends "../base.html" %}

	{% block head_title %}
    	<title>Home</title>
	{% endblock %}

{% block body_block %}
<div class="au-card">
  <div class="row">
    <div class="col-md-12">
      <div class="overview-wrap">
        <h2 class="title-1">Schedule</h2>
      </div>
    </div>
  </div>
	<br>
  <div class="section__content section__content--p30">
    <div class="table-responsive table--no-card m-b-40">
      <table
        class="table table-borderless table-striped table-earning"
        align="center"
      >
				<thead>
					<tr>
						<th></th>
						<th>Monday</th>
						<th>Tuesday</th>
						<th>Wednesday</th>
						<th>Thursday</th>
						<th>Friday</th>
					</tr>
				</thead>
        <tbody>
          <tr>
              <td>Delivery</td>
              <td>{{ schedule.monday_start }}</td>
              <td>{{ schedule.tuesday_start}}</td>
              <td>{{ schedule.wednesday_start}}</td>
              <td>{{ schedule.thursday_start}}</td>
              <td>{{ schedule.friday_start}}</td>
          </tr>
					<tr>
              <td>Meals</td>
							<td>{{ schedule.monday_start_meals }}</td>
              <td>{{ schedule.tuesday_start_meals }}</td>
              <td>{{ schedule.wednesday_start_meals }}</td>
              <td>{{ schedule.thursday_start_meals }}</td>
              <td>{{ schedule.friday_start_meals }}</td>

          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="overview-wrap">
				{% if user.user_object.type == 'PR' %}
        <h2 class="title-1">Restaurant Information</h2>
				{% else %}
				<h2 class="title-1">Program Information</h2>
				{% endif %}
      </div>
    </div>
  </div>

	<br>

  <div class="section__content section__content--p30">
      <div class="row">

        {% if user.user_object.type == 'PR' %}

            <div class="table-responsive table--no-card m-b-40">
                <table id="existingPairings"
                class="table table-borderless table-striped table-earning"
                align="center"
                >
                    <thead>
                        <tr>
                            <th>Company name</th>
                            <th>Main contact</th>
                            <th>Phone number</th>
                            <th>Schedule</th>
                            <th>Meals</th>
                            <th>Uber eats</th>
                            <th>Delivery capacity</th>
                            <th>Packaging</th>
                            <th>Health certificate</th>
                            <th>Address</th>
                        </tr>
                    </thead>
                    <tbody>
                         {% for restaurant in pairing_info %}
                        <tr>
                            <td>{{ restaurant.company_name }}</td>
                            <td>{{ restaurant.main_contact.first_name }} {{ restaurant.main_contact.last_name }}</td>
                            <td>{{ restaurant.phone_number }}</td>
                            <td>


                                {% if restaurant.schedule.monday_start != None %}
                                    <span style="color:red; font-weight:600;">M</span>
                                {% else %}
                                    <span style="color:black; font-weight:400;">M</span>
                                {% endif %}

                                {% if restaurant.schedule.tuesday_start != None %}
                                    <span style="color:red; font-weight:600;">T</span>
                                {% else %}
                                    <span style="color:black; font-weight:400;">T</span>
                                {% endif %}

                                {% if restaurant.schedule.wednesday_start != None %}
                                    <span style="color:red; font-weight:600;">W</span>
                                {% else %}
                                    <span style="color:black; font-weight:400;">W</span>
                                {% endif %}

                                {% if restaurant.schedule.thursday_start != None %}
                                    <span style="color:red; font-weight:600;">T</span>
                                {% else %}
                                    <span style="color:black; font-weight:400;">T</span>
                                {% endif %}

                                {% if restaurant.schedule.friday_start != None %}
                                    <span style="color:red; font-weight:600;">F</span>
                                {% else %}
                                    <span style="color:black; font-weight:400;">F</span>
                                {% endif %}

                            </td>
                            <td>{{ restaurant.meals }}</td>

                            {% if restaurant.uber_eats %}
                                <td>Yes</td>
                            {% else %}
                                <td>No</td>
                            {% endif %}

                            {% if restaurant.delivery_capacity %}
                                <td>Yes</td>
                            {% else %}
                                <td>No</td>
                            {% endif %}

                            {% if restaurant.packaging %}
                                <td>Yes</td>
                            {% else %}
                                <td>No</td>
                            {% endif %}

                            <td>{{ restaurant.health_certificate }}</td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        {% elif user.user_object.type == 'RE' %}

            <div class="table-responsive table--no-card m-b-40">
                <table id="existingPairings"
                class="table table-borderless table-striped table-earning"
                align="center"
                >
                    <thead>
                        <tr>
                            <th>Program name</th>
                            <th>Main contact</th>
                            <th>Phone number</th>
                            <th>Schedule</th>
                            <th>Meals</th>
                            <th>Address</th>
                        </tr>
                    </thead>
                    <tbody>
                         {% for program in pairing_info %}
                        <tr>
                            <td>{{ program.program_name }}</td>
                            <td>{{ program.main_contact.first_name }} {{ program.main_contact.last_name }}</td>
                            <td>{{ program.phone_number }}</td>
                            <td>

                                {% if program.schedule.monday_start != None %}
                                    <span style="color:red; font-weight:600;">M</span>
                                {% else %}
                                    <span style="color:black; font-weight:400;">M</span>
                                {% endif %}

                                {% if program.schedule.tuesday_start != None %}
                                    <span style="color:red; font-weight:600;">T</span>
                                {% else %}
                                    <span style="color:black; font-weight:400;">T</span>
                                {% endif %}

                                {% if program.schedule.wednesday_start != None %}
                                    <span style="color:red; font-weight:600;">W</span>
                                {% else %}
                                    <span style="color:black; font-weight:400;">W</span>
                                {% endif %}

                                {% if program.schedule.thursday_start != None %}
                                    <span style="color:red; font-weight:600;">T</span>
                                {% else %}
                                    <span style="color:black; font-weight:400;">T</span>
                                {% endif %}

                                {% if program.schedule.friday_start != None %}
                                    <span style="color:red; font-weight:600;">F</span>
                                {% else %}
                                    <span style="color:black; font-weight:400;">F</span>
                                {% endif %}


                            </td>

                            <td>{{ program.meals }}</td>

                            <td>{{ program.address }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        {% endif %}


    </div>
  </div>
</div>



{% endblock %}