project/homepage/urls.py
"""
urls for homepage
"""
import django
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r"^", include("profiles.urls", namespace="profiles")),
    url(r"^admin/", include("applications.admin_urls", namespace="admin")),
    url(r"^django/admin/", admin.site.urls),
    # url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^requests/", include("applications.requests_urls", namespace="requests")),
    url(r"^documents/", include("documents.urls", namespace="documents")),
    url(r"^", include("applications.urls", namespace="applications")),
    url(r'^settings/$', views.user_settings, name='user_settings'),
    url(r'^resources/$', views.user_resources, name='user_resources'),
    url(r"^settings/", include("applications.settings_urls", namespace="settings")),



    url(r'^password-reset/$', django.contrib.auth.views.password_reset, name='password_reset'),

    url(r'^password-reset/done/$', django.contrib.auth.views.password_reset_done, name='password_reset_done'),

    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        django.contrib.auth.views.password_reset_confirm, name='password_reset_confirm'),

    url(r'^password-reset/complete/$', django.contrib.auth.views.password_reset_complete,
        name='password_reset_complete'),
]

project/profiles/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'profiles'

urlpatterns = [
    url(r'^login', views.login_function, name='user_login'),
    url(r"^logout", views.logout_function, name="logout"),
    url(r'^signup', views.signup_function, name='register'),
]

project/profiles/models.py
# from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models

# from applications.models import ApplicationReview
# from profiles.models import Restaurant, Program, Courier





# Enum for Admin
BASIC_ADMIN = 'ADMIN'
SUPER_ADMIN = 'SUPER'
MANAGER = 'MNGR'
DEVELOPER = 'DEV'
STAFF = 'STAFF'


ADMIN_ROLE_OPTIONS = [
    (BASIC_ADMIN, 'basic admin'),
    (SUPER_ADMIN, 'super admin'),
    (MANAGER, 'manager'),
    (DEVELOPER, 'developer'),
    (STAFF, 'stuff'),
]


PROGRAM = "PR"
RESTAURANT = "RE"

USER_TYPE_OPTIONS = [
    (PROGRAM, 'Program'),
    (RESTAURANT, 'Restaurant'),
]


PHONE = "PH"
EMAIL = "EM"



PREFERRED_CONTACT = [
    (PHONE, 'Phone'),
    (EMAIL, 'Email'),
]


ADMIN = "ADM"
BASIC_USER = "BSC"

USER_TYPES = [
    (ADMIN, 'Admin'),
    (BASIC_USER, 'Basic User'),
]


class UserClassManager(BaseUserManager):
    """Manager for User class"""

    # method for creatig admins, but not super admins
    def create_staffuser(self, last_name, first_name, email, password, role, phone_number=''):
        new_account = self.create_user(phone_number=phone_number, last_name=last_name, first_name=first_name,
                                       email=email, password=password)
        new_account.staff = True

        admin_object = AdminUser.objects.create(role=role)
        new_account.admin_object = admin_object
        new_account.user_type = ADMIN
        admin_object.save(using=self._db)

        new_account.save(using=self._db)
        return new_account

    def create_basic_user(self, type, last_name, first_name, email, password, phone_number=''):
        new_account = self.create_user(phone_number=phone_number, last_name=last_name, first_name=first_name,
                                       email=email, password=password)
        user_object = BasicUser.objects.create(type=type)
        new_account.user_object = user_object
        new_account.user_type = BASIC_USER

        user_object.save(using=self._db)
        new_account.save(using=self._db)

        return new_account

    # method for creating restaurants, schools, etc.
    def create_user(self, last_name, first_name, email, password, phone_number=''):
        new_account = self.model(email=self.normalize_email(email),)
        new_account.set_password(password)

        new_account.last_name = last_name
        new_account.first_name = first_name

        new_account.phone_number = phone_number

        new_account.save(using=self._db)
        return new_account

    # method for creating superadmins
    def create_superuser(self, last_name, first_name, email, password, phone_number=''):
        new_account = self.create_user(phone_number=phone_number, last_name=last_name, first_name=first_name,
                                       email=email, password=password)
        new_account.staff = True
        new_account.admin = True

        admin_object = AdminUser.objects.create(role=SUPER_ADMIN)
        new_account.admin_object = admin_object
        new_account.user_type = ADMIN
        admin_object.save(using=self._db)

        new_account.save(using=self._db)
        return new_account

    # add any required fields here other than email and password
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'


class UserClass(AbstractBaseUser):
    """Class for general user - can be basic user or admin"""
    phone_number = models.CharField(verbose_name='phone number', max_length=255, unique=False, default='')
    active = models.BooleanField(default=True)

    is_active = models.BooleanField(default=True)

    email = models.EmailField(verbose_name='email', max_length=255, unique=True, )
    last_name = models.CharField(verbose_name='last name', max_length=255, unique=False, )
    first_name = models.CharField(verbose_name='first name', max_length=255, unique=False, )
    objects = UserClassManager()
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    image = models.CharField(verbose_name='user image', max_length=255, unique=False, default='defaultIcon.png')
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['first_name', 'last_name']

    user_type = models.CharField(
        max_length=20,
        choices=USER_TYPES,
        default=BASIC_USER,
    )

    user_object = models.ForeignKey('profiles.BasicUser', on_delete=models.DO_NOTHING, null=True, related_name='basic_user_parent')
    admin_object = models.ForeignKey('profiles.AdminUser', on_delete=models.DO_NOTHING, null=True, related_name='admin_user_parent')

    def has_module_perms(self, app_label):
        return True

    @property
    def is_admin(self):
        return self.admin

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

    def get_short_name(self):
        return self.first_name

    @property
    def is_staff(self):
        return self.staff

    def __str__(self):
        return self.email

class AdminUser(models.Model):
    """Model for admin user data"""
    role = models.CharField(
        max_length=20,
        choices=ADMIN_ROLE_OPTIONS,
        default=STAFF,
    )


class BasicUser(models.Model):
    """Model for basic user data"""
    type = models.CharField(
        max_length=20,
        choices=USER_TYPE_OPTIONS,
        default=RESTAURANT,
    )

    preferred_contact = models.CharField(
        max_length=20,
        choices=PREFERRED_CONTACT,
        default=EMAIL,
    )

    position = models.CharField(verbose_name='position/title', max_length=255, unique=False, null=True)

    restaurant = models.ForeignKey('profiles.Restaurant', on_delete=models.CASCADE, null=True)
    program = models.ForeignKey('profiles.Program', on_delete=models.CASCADE, null=True)
    courier = models.ForeignKey('profiles.Courier', on_delete=models.CASCADE, null=True)


class Schedule(models.Model):
    monday_start = models.TimeField(auto_now=False, null=True, blank=True)
    monday_end = models.TimeField(auto_now=False, null=True, blank=True)
    tuesday_start = models.TimeField(auto_now=False, null=True, blank=True)
    tuesday_end = models.TimeField(auto_now=False, null=True, blank=True)
    wednesday_start = models.TimeField(auto_now=False, null=True, blank=True)
    wednesday_end = models.TimeField(auto_now=False, null=True, blank=True)
    thursday_start = models.TimeField(auto_now=False, null=True, blank=True)
    thursday_end = models.TimeField(auto_now=False, null=True, blank=True)
    friday_start = models.TimeField(auto_now=False, null=True, blank=True)
    friday_end = models.TimeField(auto_now=False, null=True, blank=True)
    saturday_start = models.TimeField(auto_now=False, null=True, blank=True)
    saturday_end = models.TimeField(auto_now=False, null=True, blank=True)
    sunday_start = models.TimeField(auto_now=False, null=True, blank=True)
    sunday_end = models.TimeField(auto_now=False, null=True, blank=True)

    def getSchedule(self):
        schedule = {}
        if self.monday_start:
            schedule['monday_start'] = self.monday_start.strftime("%-I:%M %p")
        else:
            schedule['monday_start'] = ''
        if self.monday_end:
            schedule['monday_end'] = self.monday_end.strftime("%-I:%M %p")
        else:
            schedule['monday_end'] = ''
        if self.tuesday_start:
            schedule['tuesday_start'] = self.tuesday_start.strftime("%-I:%M %p")
        else:
            schedule['tuesday_start'] = ''
        if self.tuesday_end:
            schedule['tuesday_end'] = self.tuesday_end.strftime("%-I:%M %p")
        else:
            schedule['tuesday_end'] = ''
        if self.wednesday_start:
            schedule['wednesday_start'] = self.wednesday_start.strftime("%-I:%M %p")
        else:
            schedule['wednesday_start'] = ''
        if self.wednesday_end:
            schedule['wednesday_end'] = self.wednesday_end.strftime("%-I:%M %p")
        else:
            schedule['wednesday_end'] = ''
        if self.thursday_start:
            schedule['thursday_start'] = self.thursday_start.strftime("%-I:%M %p")
        else:
            schedule['thursday_start'] = ''
        if self.thursday_end:
            schedule['thursday_end'] = self.thursday_end.strftime("%-I:%M %p")
        else:
            schedule['thursday_end'] = ''
        if self.friday_start:
            schedule['friday_start'] = self.friday_start.strftime("%-I:%M %p")
        else:
            schedule['friday_start'] = ''
        if self.friday_end:
            schedule['friday_end'] = self.friday_end.strftime("%-I:%M %p")
        else:
            schedule['friday_end'] = ''
        if self.saturday_start:
            schedule['saturday_start'] = self.saturday_start.strftime("%-I:%M %p")
        else:
            schedule['saturday_start'] = ''
        if self.saturday_end:
            schedule['saturday_end'] = self.saturday_end.strftime("%-I:%M %p")
        else:
            schedule['saturday_end'] = ''
        if self.sunday_start:
            schedule['sunday_start'] = self.sunday_start.strftime("%-I:%M %p")
        else:
            schedule['sunday_start'] = ''
        if self.sunday_end:
            schedule['sunday_end'] = self.sunday_end.strftime("%-I:%M %p")
        else:
            schedule['sunday_end'] = ''

        return schedule


class Restaurant(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    company_name = models.CharField(verbose_name='company name', max_length=255, unique=False, )
    main_contact = models.ForeignKey('profiles.UserClass', on_delete=models.DO_NOTHING, related_name="restaurant_object", null=True)
    phone_number = models.CharField(verbose_name='phone number', max_length=255, unique=False, )
    schedule = models.ForeignKey('profiles.Schedule', on_delete=models.DO_NOTHING, null=True)
    meals = models.IntegerField()
    uber_eats = models.BooleanField(default=False)

project/profiles/views.py
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from profiles.models import UserClass
from applications.models import Notification
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from homepage import email_vendor


# logout functionality
@login_required
def logout_function(request):

    if request.user.user_type == 'ADM':
        url_redirect = '/admin'
    else:
        url_redirect = '/'

    logout(request)

    return redirect(url_redirect)


def signup_function(request):
    """Create new user account based on provided credentials"""
    if request.method == 'POST':
        email = request.POST.get("email", "")
        password = request.POST.get("password", "")
        last_name = request.POST.get("last_name", "")
        first_name = request.POST.get("first_name", "")
        type = request.POST.get("type", "")
        new_user = UserClass.objects.create_basic_user(email=email, password=password, last_name=last_name,
                                                       first_name=first_name, type=type)
        new_user.save()

        # create new notification
        notification = Notification.objects.get_or_create(notification_type='C', is_dismissed=False, \
                                           basic_user=new_user)[0]
        notification.save()

        # sending emails to admin and new user
        email_vendor.email_admin_new_signup(new_user)
        email_vendor.email_user_new_signup(new_user)

        #logs in user after signing up
        user = authenticate(email=email, password=password)
        # check if user was retrieved from the database
        if user:
            # if user is active
            if user.is_active:
                # do login
                login(request, user)
                # return response for index page
                return redirect('/')
            else:
                # return response that account is inactive
                return HttpResponse("Account is inactive")
        else:
            print("login failed")
            return HttpResponse("Invalid login details given")
    else:
        # redirect user to login page
        return render(request, 'profiles/login.html', {})


def login_function(request):
    """Login user based on provided credentials"""
    # if request type is POST
    if request.method == 'POST':
        # get credentials
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)
        # check if user was retrieved from the database
        if user:
            # if user is active
            if user.is_active:
                # do login
                login(request, user)
                # return response for index page
                return redirect('/')
            else:
                # return response that account is inactive
                return HttpResponse("Account is inactive")
        else:
            print("login failed")
            return redirect("/login")
    else:
        # redirect user to login page
        return render(request, 'profiles/login.html', {})

project/templates/profiles/admin_login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>

		<!-- Favicon -->
		<link rel="icon" href="{% static "images/icon/favicon32.jpg" %}" sizes="32x32">
		<link rel="icon" href="{% static "images/icon/favicon192.jpg" %}" sizes="192x192">

		<!-- meta tags-->
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="Feeding Canadian Kids">
		<meta name="author" content="Feeding Canadian Kids">
		<meta name="keywords" content="Feeding Canadian Kids">

		<!-- Title Page-->
		<title>Admin Login</title>

		<link href="{% static "vendor/font-awesome-4.7/css/font-awesome.min.css" %}" rel="stylesheet" media="all">
		<link href="{% static "vendor/font-awesome-5/css/fontawesome-all.min.css" %}" rel="stylesheet" media="all">

		<!-- Bootstrap CSS -->
		<link href="{% static "vendor/bootstrap-4.1/bootstrap.min.css"%}" rel="stylesheet" media="all">

		<!-- Main CSS-->
		<link href="{% static "css/main.css" %}" rel="stylesheet" media="all">
		<link rel="stylesheet" type="text/css" href="{% static "css/signup-login.css" %}">

		<link href="{% static "css/signup-login.css" %}" rel="stylesheet" media="all">

	</head>

	<body>

		<div class="limiter">
			<div class="container-login">
				<div class="wrap-login">
					<div class="login-pic js-tilt" data-tilt="">
						<img src="{% static "images/logo.png" %}" alt="Feeding Canadian Kids">
					</div>
					<div class="login-pic js-tilt-cartoon m-t-20" data-tilt="">
						<img src="{% static "images/cartoon.png" %}" alt="Feeding Canadian Kids">
					</div>

					<form id="login-form" action="{% url 'admin:admin_login' %}" method="post" class="login-form validate-form" >
						{% csrf_token %}
						<span class="login-form-title">
							Admin Login
						</span>

						<div class="wrap-input validate-input" data-validate="Valid email is required: example@fck.org">
							<input class="input" type="text" name="email" placeholder="Email" role="presentation" autocomplete="off">
							<span class="focus-input"></span>
							<span class="symbol-input">
								<i class="fa fa-envelope" aria-hidden="true"></i>
							</span>
						</div>

						<div class="wrap-input validate-input" data-validate="Password is required">
							<input class="input" type="password" name="password" placeholder="Password">
							<span class="focus-input"></span>
							<span class="symbol-input">
								<i class="fa fa-lock" aria-hidden="true"></i>
							</span>
						</div>

						<div class="container-login-form-btn">
							<button class="login-form-btn">
								Login
							</button>

							<br>
						    <br>
							<br>

						    <p><a href="{% url "password_reset" %}">Forgot your password?</a></p>
						</div>

					</form>
				</div>
			</div>
		</div>

		<!-- Jquery JS -->
		<script src="{% static "vendor/jquery-3.2.1.min.js" %}"></script>
		<!-- Bootstrap JS -->
		<script src="{% static "vendor/bootstrap-4.1/bootstrap.min.js" %}"></script>
		<!-- Animation -->
		<script src="{% static "vendor/animsition/animsition.min.js" %}"></script>

		<!--Tilt JS-->
		<script src="{% static "vendor/tilt/tilt.jquery.min.js" %}" ></script>

	</body>
</html>

project/templates/profiles/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>

		<!-- Favicon -->
		<link rel="icon" href="{% static "images/icon/favicon32.jpg" %}" sizes="32x32">
		<link rel="icon" href="{% static "images/icon/favicon192.jpg" %}" sizes="192x192">

		<!-- meta tags-->
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="Feeding Canadian Kids">
		<meta name="author" content="Feeding Canadian Kids">
		<meta name="keywords" content="Feeding Canadian Kids">

		<!-- Title Page-->
		<title>Sign Up</title>

		<link href="{% static "vendor/font-awesome-4.7/css/font-awesome.min.css" %}" rel="stylesheet" media="all">
		<link href="{% static "vendor/font-awesome-5/css/fontawesome-all.min.css" %}" rel="stylesheet" media="all">

		<!-- Bootstrap CSS -->
		<link href="{% static "vendor/bootstrap-4.1/bootstrap.min.css"%}" rel="stylesheet" media="all">
		<link href="{% static "vendor/bootstrap-select-1.13.9/css/bootstrap-select.min.css" %}" rel="stylesheet" media="all">

		<!-- Main CSS-->
		<link href="{% static "css/main.css" %}" rel="stylesheet" media="all">
		<link rel="stylesheet" type="text/css" href="{% static "css/signup-login.css" %}">

		<link href="{% static "css/signup-login.css" %}" rel="stylesheet" media="all">

	</head>

	<body>

		<div class="limiter">
			<div class="container-login">
				<div class="wrap-login">
					<div class="login-pic js-tilt" data-tilt="">
						<img src="{% static "images/logo.png" %}" alt="Feeding Canadian Kids">
					</div>
					<div class="login-pic js-tilt-cartoon m-t-20" data-tilt="">
						<img src="{% static "images/cartoon.png" %}" alt="Feeding Canadian Kids">
					</div>

					<form id="signup-form" action="{% url 'profiles:register' %}" enctype="multipart/form-data" method="post" class="login-form validate-form">
						{% csrf_token %}
						<span class="login-form-title">
							Sign Up
						</span>

						<div class="wrap-input validate-input" data-validate="First name is required">
							<input class="input" type="text" name="first_name" placeholder="First Name" role="presentation" autocomplete="off">
							<span class="focus-input"></span>
							<span class="symbol-input">
								<strong>F</strong>
							</span>
						</div>

						<div class="wrap-input validate-input" data-validate="Last name is required">
							<input class="input" type="text" name="last_name" placeholder="Last Name" role="presentation" autocomplete="off">
							<span class="focus-input"></span>
							<span class="symbol-input">
								<strong>L</strong>
							</span>
						</div>

						<div class="wrap-input validate-input" data-validate="Valid email is required: example@fck.org">
							<input class="input" type="text" name="email" placeholder="Email" role="presentation" autocomplete="off">
							<span class="focus-input"></span>
							<span class="symbol-input">
								<i class="fa fa-envelope" aria-hidden="true"></i>
							</span>
						</div>

						<div class="wrap-input validate-input" data-validate="Password is required">
							<input class="input" type="password" name="password" placeholder="Password">
							<span class="focus-input"></span>
							<span class="symbol-input">
								<i class="fa fa-lock" aria-hidden="true"></i>
							</span>
						</div>






						<div class="wrap-input m-t-5">
							<select name="type" form="signup-form" class="selectpicker" width="100">
							  <option value="RE">Restaurant</option>
							  <option value="PR">Program</option>
							</select>
						</div>





						<div class="container-login-form-btn">
							<button class="login-form-btn">
								Sign Up
							</button>
							<p class="m-t-5"> Already a user? <span id="login-link" class="link"> Log In </span></p>
						</div>

					</form>



					<form id="login-form" action="{% url 'profiles:user_login' %}" method="post" class="login-form validate-form" style="display: none;">
						{% csrf_token %}
						<span class="login-form-title">
							Login
						</span>

						<div class="wrap-input validate-input" data-validate="Valid email is required: example@fck.org">
							<input class="input" type="text" name="email" placeholder="Email" role="presentation" autocomplete="off">
							<span class="focus-input"></span>
							<span class="symbol-input">
								<i class="fa fa-envelope" aria-hidden="true"></i>
							</span>
						</div>

						<div class="wrap-input validate-input" data-validate="Password is required">
							<input class="input" type="password" name="password" placeholder="Password">
							<span class="focus-input"></span>
							<span class="symbol-input">
								<i class="fa fa-lock" aria-hidden="true"></i>
							</span>
						</div>

						<div class="container-login-form-btn">
							<button class="login-form-btn">
								Login
							</button>
							<p class="m-t-5"> Don't have an account? <span id="signup-link" class="link"> Sign Up </span></p>
							<p><a href="{% url "password_reset" %}">Forgot your password?</a></p>
						</div>

					</form>
				</div>
			</div>
		</div>

		<!-- Jquery JS -->
		<script src="{% static "vendor/jquery-3.2.1.min.js" %}"></script>
		<script src="{% static "vendor/bootstrap-select-1.13.9/popper.js" %}"></script>
		<!-- Bootstrap JS -->
		<script src="{% static "vendor/bootstrap-4.1/bootstrap.min.js" %}"></script>
		<!-- Animation -->
		<script src="{% static "vendor/animsition/animsition.min.js" %}"></script>

		<!--Tilt JS-->
		<script src="{% static "vendor/tilt/tilt.jquery.min.js" %}" ></script>

		<script src="{% static "vendor/bootstrap-select-1.13.9/js/bootstrap-select.min.js" %}"></script>

		<script>
			$('.js-tilt').tilt({
				scale: 1.1
			})

			$('.js-tilt-cartoon').tilt({
				scale: 0.9
			})

			$("#login-link").on('click', function(e) {
				$("#signup-form").hide("fast");
				$("#login-form").show("fast");
			});

			$("#signup-link").on('click', function(e) {
				$("#signup-form").show("fast");
				$("#login-form").hide("fast");
			});
		</script>

	</body>
</html>

project/templates/profiles/profile.html
{% extends "../base.html" %}
{% load staticfiles %}
	{% block head_title %}
    	<title>Profile Page</title>
	{% endblock %}

{% block body_block %}

<div class="au-card">
	<div class="row">
		<div class="col">
			<div class="d-inline">
				<img width="50" src="/static/images/icon/profile_image/{{ view_user.image }}" alt="Profile Image">
				<h3 class="m-t-10 m-b-5">{{ view_user.first_name|add:" "|add:view_user.last_name }}</h3>
				{% if view_user.user_type == 'BSC' %}
					{% if view_user.user_object.type == 'RE' and view_user.user_object.restaurant %}
						<a href="/admin/restaurant/{{ view_user.user_object.restaurant.id }}/">
							<h4>{{ view_user.user_object.restaurant.company_name }} <span>(Restaurant)</span></h4>
						</a>
					{% elif view_user.user_object.type == 'PR' and view_user.user_object.program %}
						<a href="/admin/program/{{ view_user.user_object.program.id }}/">
							<h4>{{ view_user.user_object.program.program_name }} <span>(Program)</span></h4>
						</a>
					{% else %}
					 <h4>Has not applied for {% if view_user.user_object.type == 'PR' %}program{% else %}restaurant{% endif %} yet</h4>
					{% endif %}
				{% else %}
					<h4>Admin</h4>
				{% endif %}
			</div>
		</div>
	</div>
	<br>
	<div class="row m-t-15">
		<div class="col">

			<form id="update_user" action="{% url 'admin:edit_user_profile' id=view_user.id %}" method="post">
				{% csrf_token %}
				<div class="form-group row">
			    <label for="email" class="col-sm-3 col-form-label">Email</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="email" name="email" value="{{ view_user.email }}">
			    </div>
			  </div>

			  <div class="form-group row">
			    <label for="first_name" class="col-sm-3 col-form-label">First Name</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="first_name" name="first_name" value="{{ view_user.first_name }}">
			    </div>
			  </div>

				<div class="form-group row">
			    <label for="first_name" class="col-sm-3 col-form-label">Last Name</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="last_name" name="last_name" value="{{ view_user.last_name }}">
			    </div>
			  </div>

				<div class="form-group row">
			    <label for="phone_number" class="col-sm-3 col-form-label">Phone Number</label>
			    <div class="col-sm-8">
			      <input type="text" class="form-control" id="phone_number" name="phone_number" value="{{ view_user.phone_number }}">
			    </div>
			  </div>

				<div class="form-group row">
			    <label for="phone_number" class="col-sm-3 col-form-label">Status</label>
			    <div class="col-sm-8">
						<select id="is_active" name="is_active" class="selectpicker" title="Status" data-width="100%">
							<option value="1" {% if view_user.active %}selected{% endif %}> Active </option>
							<option value="0" {% if not view_user.active %}selected{% endif %}> Inactive </option>
						</select>
			    </div>
			  </div>

				<div class="form-group row">

					{% if user.user_object.type == 'RE' %}
					<label for="c_name" class="col-sm-3 col-form-label">Restaurant Name</label>
					{% elif user.user_object.type == 'PR' %}
					<label for="c_name" class="col-sm-3 col-form-label">Programe Name</label>
					{% endif %}
			    <div class="col-sm-8">
						{% if user.user_object.restaurant %}
							<strong>{{ user.user_object.restaurant }}</strong>
						{% elif user.user_object.type == 'PR' %}
						<label for="c_name" class="col-sm-3 col-form-label">Programe Name</label>
						{% endif %}
			    </div>
			  </div>

				<div class="row">
					<div class="col">
						<button id="update-btn" type="submit" class="btn btn-success float-right" disabled>Update</button>
					</div>
				</div>



			</form>

		</div>
	</div>

</div>
{% endblock %}




{% block javascript_block %}
<script type="text/javascript">

	$('#update_user').on('change', function(e) {
		$('#update-btn').prop('disabled', false);
	});

</script>
{% endblock %}

project/templates/profiles/resources.html
{% extends "../base.html" %}
{% load staticfiles %}


{% block head_title %}
    <title>Settings</title>
{% endblock %}

{% block body_block %}
<div class="section__content section__content--p30">
        <div class="container-fluid">
          <div class = "au-card">
  
                        <div class="col-lg-12">
                          
                          
                          <div class="table-responsive table--no-card m-b-40">
                            <table
                              class="table table-borderless table-striped table-earning"
                              align="center"
                            >
                              <thead>
                                <tr>
                                  <th>filename</th>
                                  <th>size</th>
                                </tr>
                              </thead>
        
                              <tbody id='fileTable'>
                                {% for r in resources %}
                                  <tr>
                                    <td>{{ r.0 }}</td>
                                    <td>{{ r.1 }}</td>
                                    <td>
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                      <button class='reviewButton' type="submit" name="download" value="{{r.0}}" >Download</button>
                                      </form>
                                    </td>
                                  </tr>
                                {% endfor %}
                              </tbody>
                            </table>
                    
                        </div>
                    </div>
        </div>
    </div>
</div>

{% endblock %}

project/templates/profiles/signup.html
{% extends "profiles/base.html" %}

{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}
    </div>
  </div>
{% endblock %}